### ISSUE TITLE
caddy bulid error 

### ISSUE THREAD

**Issue by Shinhocheol** [jptosso/coraza-demo-stack#1]
/root/go/pkg/mod/github.com/quic-go/quic-go@v0.37.3/internal/handshake/crypto_setup.go:362:37: cannot use h.allow0RTT (variable of type bool) as tls.QUICSessionTicketOptions value in argument to h.conn.SendSessionTicket

For me, the environment is 
go version 1.9.

**Comment by jptosso** [comment]
Updated package to latest version!
